---
title: "Varicella immunization proportion, coHealth Kensington, 2017-2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(broom)
library(plotly)
```

## Varicella immunisation age 70-79 years, PenCAT data up to April 2018

Also weekly Doctor's Control panel (DCP) data from August 2017 to January 2018

```{r data}

pencat_report <- data.frame(Date = as.Date('2018/04/03'), Vaccinated = 91, Total = 181)

pencat_report[2,] <- list(as.Date('2018/03/16'),88,180)
pencat_report[3,] <- list(as.Date('2018/02/10'),82,173)
pencat_report[4,] <- list(as.Date('2017/12/28'),77,172)
pencat_report[5,] <- list(as.Date('2017/12/01'),74,166)
pencat_report[6,] <- list(as.Date('2017/11/03'),71,166)
pencat_report[7,] <- list(as.Date('2017/10/03'),64,164)
pencat_report[8,] <- list(as.Date('2017/09/05'),63,164)
pencat_report[9,] <- list(as.Date('2017/08/01'),58,165)
pencat_report[10,] <- list(as.Date('2017/07/06'),58,164)

dcp_report <- data.frame(Date =  as.Date('2017/08/13'), Proportion = 0.26)

dcp_report[2,] <- list(as.Date('2017/08/20'),0.19)
dcp_report[3,] <- list(as.Date('2017/08/27'),0.24)
dcp_report[4,] <- list(as.Date('2017/09/10'),0.42)
dcp_report[5,] <- list(as.Date('2017/09/17'),0.35)
dcp_report[6,] <- list(as.Date('2017/09/24'),0.34)
dcp_report[7,] <- list(as.Date('2017/10/01'),0.45)
dcp_report[8,] <- list(as.Date('2017/10/22'),0.44)
dcp_report[9,] <- list(as.Date('2017/10/29'),0.50)
dcp_report[10,] <- list(as.Date('2017/11/05'),0.48)
dcp_report[11,] <- list(as.Date('2017/11/12'),0.42)
dcp_report[12,] <- list(as.Date('2017/11/19'),0.57)
dcp_report[13,] <- list(as.Date('2017/12/03'),0.53)
dcp_report[14,] <- list(as.Date('2017/12/17'),0.75)
dcp_report[15,] <- list(as.Date('2017/12/31'),0.45)
dcp_report[16,] <- list(as.Date('2018/01/07'),0.51)


```

## Plots

```{r plot_pencat}

pencat_report$Proportion <- pencat_report$Vaccinated/pencat_report$Total
pencat_report$numericDate <- as.numeric(pencat_report$Date) 
m <- augment(loess(Proportion ~ numericDate, # loess localized regression accepts numbers, not dates
                   data = pencat_report))
m$Date <- pencat_report$Date # but plotly plots require, in this case, dates, not numbers!

p_pencat <- pencat_report %>%
  plot_ly(x=~Date, y=~Proportion,
          type='scatter', mode='markers') %>%
  add_lines(y = ~fitted(loess(Proportion ~ as.numeric(Date))),
            line = list(color = 'rgba(7,164,181,1)'),
            showlegend = FALSE) %>%
  add_ribbons(data = m,
              x = ~Date,
              ymin = ~.fitted - 1.96 * .se.fit,
              ymax = ~.fitted + 1.96 * .se.fit,
              line = list(color = 'rgba(7,164,181,0.05)'),
              fillcolor = 'rgba(7,164,181,0.2)',
              showlegend = FALSE) %>% 
  layout(title = 'Varicella zoster vaccination
         proportion of 70-79 year olds (PenCAT report)
         coHealth Kensington, 2017-2018')

p_pencat

```

```{r plot_dcp}

dcp_report$numericDate <- as.numeric(dcp_report$Date)
m <- augment(loess(Proportion ~ numericDate,
                   data = dcp_report))
m$Date <- dcp_report$Date

p_dcp <- dcp_report %>%
  plot_ly(x=~Date, y=~Proportion,
          type='scatter', mode='markers') %>%
  add_lines(y = ~fitted(loess(Proportion ~ as.numeric(Date))),
            line = list(color = 'rgba(7,164,181,1)'),
            showlegend = FALSE) %>%
  add_ribbons(data = m,
              x = ~Date,
              ymin = ~.fitted - 1.96 * .se.fit,
              ymax = ~.fitted + 1.96 * .se.fit,
              line = list(color = 'rgba(7,164,181,0.05)'),
              fillcolor = 'rgba(7,164,181,0.2)',
              showlegend = FALSE) %>% 
  layout(title = 'Varicella zoster vaccination
         proportion of 70-79 year olds
         seen in each week (DCP report)
         coHealth Kensington, 2017-2018')

p_dcp

```